#!/bin/bash


####################
##   PROMPT [PS1] VARIABLES
##    COLORS IN USE FOR PS
PSC_NC='\[\e[0m\]'                                  ### Color Reset - No Color
PSC_RD='\[\e[0;41m\]'                               ### Red BG - White FG
PSC_GN='\[\e[0;32m\]'                               ### Green with black text
PSC_CY='\[\e[0;96m\]'                               ### Cyan 2
PSC_MA='\[\e[1;35m\]'                               ### Magenta Bold
PSC_RDW='\[\e[0;101m\]'                             ### Red Hi Intense BG - White FG
PSC_YW='\[\e[38;5;220m\]'                           ### Yellow
PSC_WHT='\[\e[38;5;15m\]'                           ### White
PSC_GN2='\[\e[38;5;46m\]'                           ### Neon Green
PSC_CY2='\[\e[38;5;51m\]'                           ### Cyan
PSC_PRP='\[\e[38;5;147m\]'                          ### Purple          [GreenYellow] - Hostname
PSC_RD2='\[\e[38;5;196m\]'                          ### Red FG - Black BG
PSC_YW2='\[\e[38;1;33m\]'                           ### Neon Yellow
PSC_BLK='\[\e[38;5;240m\]'                          ### Black
#PSC_RD="$PSC_NC\[\e[5;37;41m\]"                    ### Red BG - White FG

##    LINE 1 OF 3 SETUP : DATE/TIME BOX [(INSTANCES}] PROD ALERT
export PS_DT="$PSC_CY2\d \@$PSC_NC"                 ### Date/Time         - Cyan
export PSUSR="$PSC_MA\u$PSC_NC"                     ### User              - Magenta
export PS_AT="$PSC_GN2@$PSC_NC"                     ### @                 - Neon Green
export PSHOST="$PSC_PRP\H:$PSC_NC"                  ### Hostname          - Yellow
export PSPWD="$PSC_WHT\w$PSC_NC"                    ### PWD               - White - with color reset
export PSPROMPT="$PSC_GN2] $PSC_NC"                 ### ]                 - Neon Green
#export PSUSR="$PSC_PRP\u$PSC_NC"                    ### User              - Purple

####################
#|  SET PROMPT [PS1] [PS2]
export PS1="\n${PS_DT}\n\
${PSUSR}${PS_AT}${PSHOST}${PSPWD}${PSPROMPT}"

export PS2="${PSC_GN2}continue-> ${PSC_NC}"

SPACER="    "

##  PROMPT_COMMAND to set the title bar of the putty window                                ::: #
##  history -a  # append history lines from this session to the history file.              ::: #
PROMPT_COMMAND='history -a; if [[ ! ( $(date +"%T") < "$prodStartTime" || $(date +"%T") > "$prodEndTime" ) ]]; then MESSAGE="ON WORK "; else MESSAGE="OFF WORK"; fi; echo -ne " \e]0; ${USER}@${HOSTNAME}: ${PWD} ${SPACER}${SPACER}|${SPACER}$PC_HOST${SPACER}|${SPACER}[QPS-Jump-Host]${SPACER}|${SPACER}$(echo ${MESSAGE})${SPACER}| \007"'

